routes/web.php
<?php

use App\Http\Controllers\LoginClientesController;
use App\Http\Controllers\RegistroController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProyectosController;
use App\Http\Controllers\CarritoCompraController;
use App\Http\Controllers\LoginBackendController;
use App\Http\Controllers\HomeBackendController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\ProductosController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProyectosBackController;
use App\Http\Controllers\ComprarProducto;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CondicionesController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\VentasBackController;
use App\Http\Controllers\Ventas2Controller;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('/home', [HomeController::class, 'index'])->name('home.index');

Route::get('/productos', [ProductosController::class, 'index']);
Route::post('/productos/ver/{id}', [ProductosController::class, 'show'])->name('producto.show');
Route::GET('/productos/calculo', [ProductosController::class, 'sum'])->name('producto.sum');

Route::post('/productos/ver/{id}/agregarcarrito', [ProductosController::class, 'store'])->name('producto.store');


Route::get('/productos/comprar/1', [ComprarProducto::class, 'index'])->name('comprar.index');
Route::get('/productos/comprar', [ComprarProducto::class, 'show'])->name('comprar.show');

Route::get('/proyectos', [ProyectosController::class, 'index'])->name('proyectos.index');
Route::post('/proyectos/ver/{id}', [ProyectosController::class, 'show'])->name('proyectos.show');

Route::get('/proyectos/vista', [ProyectosController::class, 'indexP'])->name('proyectos.indexP');



Route::get('/condiciones', [CondicionesController::class, 'index'])->name('condiciones.index');


Route::get('/login', [LoginClientesController::class, 'index'])->name('login.index');
Route::get('/login', [LoginClientesController::class, 'logout'])->name('login.logout');
Route::post('/login', [LoginClientesController::class, 'store'])->name('login.store');


//rutas para el registro de la vista cliente
Route::get('/registro', [RegistroController::class, 'index'])->name('registro.index');
Route::post('registro', [RegistroController::class, 'store'])->name('registro.store');
//rutas cliente vista
Route::get('/carritocompra', [CarritoCompraController::class, 'index'])->name('carritocompra.index');
Route::delete('/carritocompra/{id}', [CarritoCompraController::class, 'destroy'])->name('carritocompra.destroy');

Route::get('/compra', [CarritoCompraController::class, 'indexCompra'])->name('compra.indexCompra');
Route::post('/compra', [CarritoCompraController::class, 'updateCompra'])->name('compra.updateCompra');

Route::get('/factura', [CarritoCompraController::class, 'factura'])->name('compra.factura');
Route::get('factura/{id}/{numero_orden}', [Ventas2Controller::class, 'showcliente'])->name('ventas.showcliente');

//rutas para backend
 Route::group(['prefix' => 'backend'], function () {

        Route::get('/loginbackend', [LoginBackendController::class, 'index'])->name('loginbackend.index');
        Route::get('/loginbackend', [LoginBackendController::class, 'logout'])->name('loginbackend.logout');
        Route::post('/loginbackend', [LoginBackendController::class, 'store'])->name('loginbackend.store');


        //Productos
        Route::get('/homebackend', [HomeBackendController::class, 'index'])->middleware('can:homebackend.index')->name('homebackend.index');
        Route::get('/homebackend/productos', [ProductoController::class, 'index'])->middleware('can:homebackend.index')->name('productosbackend.index');
        Route::post('/homebackend/productos', [ProductoController::class, 'store'])->middleware('can:homebackend.index')->name('productosbackend.store');
        Route::delete('/homebackend/productos/{id}', [ProductoController::class, 'destroy'])->middleware('can:homebackend.index')->name('productosbackend.destroy');
        Route::post('/homebackend/productos/{id}/editar', [ProductoController::class, 'edit'])->name('productosbackend.edit');
        Route::post('/homebackend/productos/{id}/actualizado', [ProductoController::class, 'update'])->middleware('can:homebackend.index')->name('productosbackend.update');
        //Usuarios Ventas2Controller
        Route::get('/homebackend/ventas', [Ventas2Controller::class, 'index'])->middleware('can:homebackend.index')->name('ventas.index');
        Route::get('homebackend/ventas/{id}/{numero_orden}', [Ventas2Controller::class, 'show'])->name('ventas.show');
        Route::delete('/homebackend/ventas/{id}', [Ventas2Controller::class, 'destroy'])->middleware('can:homebackend.index')->name('ventas.destroy');

        Route::resource('homebackend/users', UserController::class)->names('backend.users');
        //proyectos
        Route::resource('homebackend/proyectos', ProyectosBackController::class)->middleware('can:homebackend.index')->names('backend.proyectos');

        Route::resource('homebackend/banners', BannerController::class)->middleware('can:homebackend.index')->names('backend.banner');



});

app/Models/Proyecto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyecto extends Model
{
    use HasFactory;
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;
use App\Models\Proyecto;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class ProyectosController extends Controller
{
    public function index() {
        $proyectos = DB::table('proyectos')
        ->select('proyectos.*')
        ->get();
         //dd( $productos);
        return view ('proyectos')-> with('proyectos',$proyectos);
    }
    

    public function indexP() {
        return view ('vistaproyecto');
    }
    public function show(Proyecto $id)
    {
        $proyecto = Proyecto::find($id);
        return view ('vistaproyecto',compact('proyecto'));
    }
}

resources/views/backend/proyectos/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar Proyecto</h1>
@stop

@section('content')
@if (session('info'))
    <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
    </div>
    
@endif
<form action="{{route('backend.proyectos.update',$proyecto )}}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('put')
<div class="card">
    <div class="card-body">
        <p class="h5">Nombre:</p>
        <input class="form-control" name="nombre" value="{{$proyecto->nombre}}" required size="200" maxlength="200">
        <p class="h5">Descripcion:</p>
        <input class="form-control" name=descripcion value="{{$proyecto->descripcion}}" required size="1000" maxlength="1000">
        <p class="h5">Imagen Principal:</p>
        <img src="{{asset('storage').'/'.$proyecto->foto}}" alt="" width="60" required>
        <input type="file" class="form-control" id="recipient-name" name="foto" required>
        <p class="h5">Imagen:</p>
        <img src="{{asset('storage').'/'.$proyecto->foto2}}" alt="" width="60">
        <input type="file" class="form-control" id="recipient-name" name="foto2" required>
        <p class="h5">Imagen:</p>
        <img src="{{asset('storage').'/'.$proyecto->foto3}}" alt="" width="60">
        <input type="file" class="form-control" id="recipient-name" name="foto3" required>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
</div>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/backend/proyectos/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Lista de Proyectos</h1>
@stop

@section('content')
    @livewire('proyectos-index')
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop