routes/web.php
<?php

use App\Http\Controllers\LoginClientesController;
use App\Http\Controllers\RegistroController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProyectosController;
use App\Http\Controllers\CarritoCompraController;
use App\Http\Controllers\LoginBackendController;
use App\Http\Controllers\HomeBackendController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\ProductosController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProyectosBackController;
use App\Http\Controllers\ComprarProducto;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CondicionesController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\VentasBackController;
use App\Http\Controllers\Ventas2Controller;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('/home', [HomeController::class, 'index'])->name('home.index');

Route::get('/productos', [ProductosController::class, 'index']);
Route::post('/productos/ver/{id}', [ProductosController::class, 'show'])->name('producto.show');
Route::GET('/productos/calculo', [ProductosController::class, 'sum'])->name('producto.sum');

Route::post('/productos/ver/{id}/agregarcarrito', [ProductosController::class, 'store'])->name('producto.store');


Route::get('/productos/comprar/1', [ComprarProducto::class, 'index'])->name('comprar.index');
Route::get('/productos/comprar', [ComprarProducto::class, 'show'])->name('comprar.show');

Route::get('/proyectos', [ProyectosController::class, 'index'])->name('proyectos.index');
Route::post('/proyectos/ver/{id}', [ProyectosController::class, 'show'])->name('proyectos.show');

Route::get('/proyectos/vista', [ProyectosController::class, 'indexP'])->name('proyectos.indexP');



Route::get('/condiciones', [CondicionesController::class, 'index'])->name('condiciones.index');


Route::get('/login', [LoginClientesController::class, 'index'])->name('login.index');
Route::get('/login', [LoginClientesController::class, 'logout'])->name('login.logout');
Route::post('/login', [LoginClientesController::class, 'store'])->name('login.store');


//rutas para el registro de la vista cliente
Route::get('/registro', [RegistroController::class, 'index'])->name('registro.index');
Route::post('registro', [RegistroController::class, 'store'])->name('registro.store');
//rutas cliente vista
Route::get('/carritocompra', [CarritoCompraController::class, 'index'])->name('carritocompra.index');
Route::delete('/carritocompra/{id}', [CarritoCompraController::class, 'destroy'])->name('carritocompra.destroy');

Route::get('/compra', [CarritoCompraController::class, 'indexCompra'])->name('compra.indexCompra');
Route::post('/compra', [CarritoCompraController::class, 'updateCompra'])->name('compra.updateCompra');

Route::get('/factura', [CarritoCompraController::class, 'factura'])->name('compra.factura');
Route::get('factura/{id}/{numero_orden}', [Ventas2Controller::class, 'showcliente'])->name('ventas.showcliente');

//rutas para backend
 Route::group(['prefix' => 'backend'], function () {

        Route::get('/loginbackend', [LoginBackendController::class, 'index'])->name('loginbackend.index');
        Route::get('/loginbackend', [LoginBackendController::class, 'logout'])->name('loginbackend.logout');
        Route::post('/loginbackend', [LoginBackendController::class, 'store'])->name('loginbackend.store');


        //Productos
        Route::get('/homebackend', [HomeBackendController::class, 'index'])->middleware('can:homebackend.index')->name('homebackend.index');
        Route::get('/homebackend/productos', [ProductoController::class, 'index'])->middleware('can:homebackend.index')->name('productosbackend.index');
        Route::post('/homebackend/productos', [ProductoController::class, 'store'])->middleware('can:homebackend.index')->name('productosbackend.store');
        Route::delete('/homebackend/productos/{id}', [ProductoController::class, 'destroy'])->middleware('can:homebackend.index')->name('productosbackend.destroy');
        Route::post('/homebackend/productos/{id}/editar', [ProductoController::class, 'edit'])->name('productosbackend.edit');
        Route::post('/homebackend/productos/{id}/actualizado', [ProductoController::class, 'update'])->middleware('can:homebackend.index')->name('productosbackend.update');
        //Usuarios Ventas2Controller
        Route::get('/homebackend/ventas', [Ventas2Controller::class, 'index'])->middleware('can:homebackend.index')->name('ventas.index');
        Route::get('homebackend/ventas/{id}/{numero_orden}', [Ventas2Controller::class, 'show'])->name('ventas.show');
        Route::delete('/homebackend/ventas/{id}', [Ventas2Controller::class, 'destroy'])->middleware('can:homebackend.index')->name('ventas.destroy');

        Route::resource('homebackend/users', UserController::class)->names('backend.users');
        //proyectos
        Route::resource('homebackend/proyectos', ProyectosBackController::class)->middleware('can:homebackend.index')->names('backend.proyectos');

        Route::resource('homebackend/banners', BannerController::class)->middleware('can:homebackend.index')->names('backend.banner');



});

app/Http/Livewire/BannerIndex.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Banner;
use Livewire\WithPagination;

class BannerIndex extends Component
{
    use WithPagination;
    protected $paginationTheme='bootstrap';
    public function render()
    {        
        $banners= Banner::paginate();
        return view('livewire.banner-index',compact('banners'));
    }
}

app/Http/Livewire/ProyectosIndex.php
<?php

namespace App\Http\Livewire;
use App\Models\Proyecto;
use Livewire\Component;
use Livewire\WithPagination;
class ProyectosIndex extends Component
{
    use WithPagination;
    public $search;
    protected $paginationTheme='bootstrap';
    public function updatingSearch(){
    $this->resetPage();
    }

    public function render()
    {
        $proyectos = Proyecto::where('nombre', 'like', '%'.$this->search.'%')->paginate();
        return view('livewire.proyectos-index', compact('proyectos'));
    }
}

app/Http/Livewire/UsersIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Model_has_role;
use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;


class UsersIndex extends Component
{
    use WithPagination;
    public $search;
    protected $paginationTheme='bootstrap';
    public function updatingSearch(){
        $this->resetPage();
    }
    public function render()
    {
            $users = Model_has_role::Join('users', 'users.id', '=', 'model_id')
            ->orderBy('id', 'ASC')
            ->get();

        return view('livewire.users-index', compact('users'));
    }
}

app/Http/Livewire/VentasIndex.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Carritocompra;
use Livewire\WithPagination;
use Illuminate\Support\Facades\DB;

class VentasIndex extends Component
{
    use WithPagination;
    public $search;
    protected $paginationTheme='bootstrap';
    public function render()
    {
        $carritos = DB::table('carritocompras')
            ->select('users.id','users.nombre','users.email','users.telefono','carritocompras.idCliente'
            ,'carritocompras.numero_orden','carritocompras.nombres','carritocompras.apellidos')
           ->selectRaw('count(carritocompras.numero_orden)')
            ->join('users', 'users.id', '=', 'carritocompras.idCliente')
            ->GROUPBY('users.id','carritocompras.numero_orden','users.email','users.telefono','users.nombre','carritocompras.idCliente'
            ,'carritocompras.nombres','carritocompras.apellidos')
            ->get();
        //dd( $productos);
        return view('livewire.ventas-index', compact('carritos'));
    }
}

resources/views/livewire/banner-index.blade.php
    <!-- Modal -->
    <!-- Button trigger modal -->

    <body>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
            data-whatever="@mdo">Nuevo</button>


        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Nuevo Banner</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('backend.banner.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Foto:</label>
                                <input type="file" class="form-control" id="recipient-name" name="foto">
                            </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Crear</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card">
            @livewireStyles
            <div class="card-header">
                <input wire:model="search" class="form-control" placeholder="Ingrese el Nombre  de un Proyecto">
            </div>
            @if ($banners->count())

                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Fotos</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($banners as $banner)
                                <tr>
                                    <td>{{ $banner->id }}</td>
                                    <td>
                                        <img src="{{ asset('storage') . '/' . $banner->foto }}" alt=""
                                            width="60">
                                    </td>
                                    <td width="10px">
                                        <a class="btn btn-primary"
                                            href="{{ route('backend.banner.edit', $banner) }}">Editar</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('backend.banner.destroy', $banner) }}" method="post">

                                            @csrf
                                            @method('delete')
                                            <input type="hidden" name="id" value="$banner">
                                            <input type="hidden" namespace="_method" value="delete">
                                            <button type="submit" class="btn btn-primary btnModalEliminar"
                                                data-id="$banner">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                    fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path
                                                        d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </form>
                        </tbody>
                    </table>
                </div>
            @else
                <div class="card-body">
                    <strong>No hay Registros</strong>

                </div>


            @endif
        </div>
        @livewireScripts
    </body>

resources/views/livewire/proyectos-index.blade.php
    <!-- Modal -->
    <!-- Button trigger modal -->

    <body>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
            data-whatever="@mdo">Nuevo</button>


        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Nuevo Proyecto</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('backend.proyectos.store') }}" method="POST"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Nombre:</label>
                                <input type="text" class="form-control" id="recipient-name" name="nombre" required>
                            </div>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Descripcion:</label>
                                <input type="text" class="form-control" id="recipient-name" name="descripcion"
                                    required>
                            </div>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Imagen Principal:</label>
                                <input type="file" class="form-control" id="recipient-name" name="foto">
                            </div>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Imagen:</label>
                                <input type="file" class="form-control" id="recipient-name" name="foto2">
                            </div>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Imagen:</label>
                                <input type="file" class="form-control" id="recipient-name" name="foto3">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                <button type="submit" class="btn btn-primary">Crear</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
        <div class="card">
            @livewireStyles
            <div class="card-header">
                <input wire:model="search" class="form-control" placeholder="Ingrese el Nombre  de un Proyecto">
            </div>
            @if ($proyectos->count())

                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Principal</th>
                                <th>Foto</th>
                                <th>Foto</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($proyectos as $proyecto)
                                <tr>
                                    <td>{{ $proyecto->id }}</td>
                                    <td>{{ $proyecto->nombre }}</td>
                                    <td>{{ $proyecto->descripcion }}</td>
                                    <td>
                                        <img src="{{ asset('storage') . '/' . $proyecto->foto }}" alt=""
                                            width="60">
                                    </td>
                                    <td>
                                        <img src="{{ asset('storage') . '/' . $proyecto->foto2 }}" alt=""
                                            width="60">
                                    </td>
                                    <td>
                                        <img src="{{ asset('storage') . '/' . $proyecto->foto3 }}" alt=""
                                            width="60">
                                    </td>
                                    <td width="10px">
                                        <a class="btn btn-primary"
                                            href="{{ route('backend.proyectos.edit', $proyecto) }}">Editar</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('backend.proyectos.destroy', $proyecto) }}"
                                            method="post">

                                            @csrf
                                            @method('delete')
                                            <input type="hidden" name="id" value="$proyecto">
                                            <input type="hidden" namespace="_method" value="delete">
                                            <button type="submit" class="btn btn-primary btnModalEliminar"
                                                data-id="$proyecto">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                    fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                    <path
                                                        d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </form>
                        </tbody>
                    </table>
                </div>
            @else
                <div class="card-body">
                    <strong>No hay Registros</strong>

                </div>


            @endif
            @livewireScripts
        </div>

    </body>

resources/views/livewire/users-index.blade.php
<div>
    <!-- Modal -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
        data-whatever="@mdo">Nuevo</button>
    <br>
    <br>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Nuevo Usuario</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('backend.users.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Nombre:</label>
                            <input type="text" class="form-control" id="recipient-name" name="nombre" required>
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Apellido:</label>
                            <input type="text" class="form-control" id="recipient-name" name="apellido" required>
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Email:</label>
                            <input type="text" class="form-control" id="recipient-name" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Telefono:</label>
                            <input type="number" class="form-control" id="recipient-name" name="telefono" required>
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">password:</label>
                            <input type="password" class="form-control" id="recipient-name" name="password" required>
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el Nombre o Correo de un Usuario">
        </div>
        @if ($users->count())

            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Telefono</th>
                            <th>Email</th>
                            <th>Rol</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->nombre }}</td>
                                <td>{{ $user->apellido }}</td>
                                <td>{{ $user->telefono }}</td>
                                <td>{{ $user->email }}</td>
                                <td></td>
                                <td width="10px">
                                    <a class="btn btn-primary"
                                        href="{{ route('backend.users.edit', $user) }}">Editar</a>
                                </td>
                                <td>
                                    <form action="{{ route('backend.users.destroy', $user) }}" method="post">

                                        @csrf
                                        @method('delete')
                                        <input type="hidden" name="id" value="$user">
                                        <input type="hidden" namespace="_method" value="delete">
                                        <button type="submit" class="btn btn-primary btnModalEliminar" data-id="$user">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                                <path
                                                    d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                            </svg>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <br>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        @else
            <div class="card-body">
                <strong>No hay Registros</strong>

            </div>


        @endif
    </div>

</div>

resources/views/livewire/ventas-index.blade.php
<div class="card">
    <div class="card-header">
        <input wire:model="search" class="form-control" placeholder="Ingrese el Nombre o Correo de un Usuario">
    </div>
    @if ($carritos->count())

        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Numero de Orden</th>
                        <th>ID Cliente</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Editar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($carritos as $carrito)
                        <tr>
                            <td>{{ $carrito->numero_orden }}</td>
                            <td>{{ $carrito->idCliente }}</td>
                            <td>{{ $carrito->email }}</td>
                            <td>{{ $carrito->telefono }}</td>
                            <td>
                                <form action="{{ route('backend.ventas.show', [$carrito->id, $carrito->numero_orden]) }}" style="margin-right:10px;">
                                    <input type="hidden" namespace="_method" value="show">
                                    <button type="submit" class="btn btn-primary " data-id="{{ $carrito->id }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                            <path
                                                d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                        </svg>
                                    </button>
                                </form>
                            </td>

                            <td>
                                <a class="btn btn-primary" href="">Eliminar</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <br>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
        </div>
    @else
        <div class="card-body">
            <strong>No hay Registros</strong>

        </div>


    @endif
</div>